name: Main Environment Pipeline

on:
  push:
    branches:
      - feature/*
  workflow_dispatch:

jobs:
  # DEV
  dev-plan:
    name: DEV
    if: ${{ github.event_name != 'push' || startsWith(github.ref, 'refs/heads/feature/') }}
    uses: ./.github/workflows/env-template.yaml
    with:
      environment: dev
      step: plan

  dev-apply:
    name: DEV
    needs: dev-plan
    if: ${{ github.event_name != 'push' || startsWith(github.ref, 'refs/heads/feature/') }}
    uses: ./.github/workflows/env-template.yaml
    with:
      environment: dev
      step: apply

  # NPR
  npr-plan:
    name: NPR
    needs: dev_plan
    if: ${{ github.event_name != 'push' || startsWith(github.ref, 'refs/heads/feature/') }}
    uses: ./.github/workflows/env-template.yaml
    with:
      environment: npr
      step: apply

  npr-apply:
    name: NPR
    needs: npr-plan
    if: ${{ github.event_name != 'push' || startsWith(github.ref, 'refs/heads/feature/') }}
    uses: ./.github/workflows/env-template.yaml
    with:
      environment: npr
      step: apply

  # PRD
  prd-plan:
    name: PRD
    needs: npr-plan
    if: ${{ github.event_name != 'push' || startsWith(github.ref, 'refs/heads/feature/') }}
    uses: ./.github/workflows/env-template.yaml
    with:
      environment: prd
      step: plan

  prd-apply:
    name: PRD
    needs: prd-plan
    if: ${{ github.event_name != 'push' || startsWith(github.ref, 'refs/heads/feature/') }}
    uses: ./.github/workflows/env-template.yaml
    with:
      environment: prd
      step: apply
